language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - curl
    - wget
    - python-pip
    - python3-pip
    - ruby
    - ruby-dev
    - datadog
install:
- bash -x scripts/provision.sh
script:
- bash -x test.sh
